#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
E & L Wedding — static site generator.

Run:
  python3 build.py            build the live site for the current PHASE
  python3 build.py --phase2   build phase 2 into _phase2/ to look at,
                              without changing or publishing anything live

Reads every piece of copy from content.py and writes the HTML pages for the
current PHASE. Pages that don't belong to the current phase are reported as
stale so you can remove them — nothing about an unreleased page ships.

All *.html files except index.html are generated. Edit content.py, not HTML.
"""

import os
import re
import shutil
import sys

import content as C

HERE = os.path.dirname(os.path.abspath(__file__))

# Where pages get written. Normally the repo root; the preview build points it
# at _preview/ so the full site can be looked at without touching what ships.
OUT_DIR = HERE
PHASE2_DIR = os.path.join(HERE, "_phase2")
# Older/renamed output folders, cleaned up on build so a stray copy can't be
# served by Live Server or picked up by git.
LEGACY_OUT_DIRS = ["_preview", "preview", "Preview"]

# Files the preview copies alongside the generated pages so it renders properly.
PHASE2_ASSETS = ["css", "js", "orchid.jpg", "surfing.jpg",
                  "og-image.jpg", "favicon.ico", "favicon.png"]

GENERATED_BANNER = (
    "<!--\n"
    "  DO NOT EDIT THIS FILE.\n"
    "  Generated by build.py from content.py. Your changes will be overwritten\n"
    "  on the next build. Edit content.py and run: python3 build.py\n"
    "-->\n"
)

# "full" is still accepted as a synonym so an older content.py keeps working.
PHASE_2_NAMES = ("phase-2", "phase2", "full")
FULL = C.PHASE in PHASE_2_NAMES


# ---------------------------------------------------------------------------
# Shared pieces
# ---------------------------------------------------------------------------

def social_meta(page=""):
    """Open Graph + Twitter tags, used for iMessage/SMS/WhatsApp/Slack previews.

    Every URL here is absolute on purpose: link-preview crawlers do not resolve
    relative paths, so a relative og:image silently yields a picture-less card.
    """
    m = C.META
    base = C.SITE_URL.rstrip("/")
    url = f"{base}/{page}" if page else f"{base}/"
    return f"""  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="E &amp; L Wedding" />
  <meta property="og:title" content="{m['title']}" />
  <meta property="og:description" content="{m['description']}" />
  <meta property="og:url" content="{url}" />
  <meta property="og:image" content="{base}/{m['image']}" />
  <meta property="og:image:secure_url" content="{base}/{m['image']}" />
  <meta property="og:image:type" content="image/jpeg" />
  <meta property="og:image:width" content="{m['image_w']}" />
  <meta property="og:image:height" content="{m['image_h']}" />
  <meta property="og:image:alt" content="Eliza and Lucas in the water at Rockpiles" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="{m['title']}" />
  <meta name="twitter:description" content="{m['description']}" />
  <meta name="twitter:image" content="{base}/{m['image']}" />
  <meta name="theme-color" content="#bcbc49" />"""


def head(title, page=""):
    v = C.ASSET_VERSION
    return f"""<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title}</title>
  <meta name="description" content="{C.META['description']}" />
  <meta name="robots" content="noindex, nofollow" />
{social_meta(page)}
  <link rel="icon" href="favicon.ico?v={v}" sizes="any" />
  <link rel="icon" type="image/png" href="favicon.png?v={v}" sizes="180x180" />
  <link rel="apple-touch-icon" href="favicon.png?v={v}" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Cormorant+Infant:ital,wght@0,300;1,300&family=Cormorant+Upright:wght@300&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="css/wedding.css?v={v}" />
</head>"""


def meta_line(date_first=True):
    """The date — rule — place strip used in the hero and the footer."""
    d = C.WEDDING["date_display"]
    p = C.WEDDING["place"]
    if date_first:
        return (f'<span class="meta"><span class="meta__date">{d}</span>'
                f'<span class="meta__rule"></span>'
                f'<span class="meta__place">{p}</span></span>')
    return (f'<span class="meta"><span class="meta__rule"></span>'
            f'<span class="meta__date">{d}</span>'
            f'<span class="meta__place">{p}</span></span>')


def banner(current, tall, save_the_date=False):
    classes = "banner banner--tall" if tall else "banner banner--short"
    if save_the_date:
        classes += " banner--stdate"

    if save_the_date:
        body = f"""      <div class="stdate">
        <h1 class="stdate__name">E &amp; L<span class="stdate__rest"> Wedding</span></h1>
        <p class="stdate__label">{C.SAVE_THE_DATE['label']}</p>
        <p class="meta stdate__meta">
          <span class="meta__rule"></span>
          <span class="meta__date">{C.WEDDING['date_display']}</span>
          <span class="meta__place">{C.WEDDING['place']}</span>
        </p>
        <p class="stdate__tagline">{C.SAVE_THE_DATE['tagline']}</p>
      </div>
"""
    elif FULL:
        # In phase 2 the nav and wordmark live in the fixed page header
        # instead, so they can ride up the screen and settle into the bar.
        # The banner is then just the photo (and the cue, on a tall hero).
        body = ""
    else:
        body = f"""      <div>
        <div class="wordmark">
          <h1 class="wordmark__name">{C.WEDDING['names']}</h1>
          {meta_line(date_first=True)}
        </div>
      </div>
"""

    # The pulsing cue belongs to any full-height hero — it exists to say
    # "there is more below the fold". The short 260px banners open straight
    # onto their content, so a cue there would point at nothing.
    cue = '      <span class="scroll-cue" aria-hidden="true"></span>\n' if tall else ""
    inner = "wrap banner__inner"
    if FULL and tall:
        inner += " banner__inner--cue-only"   # cue is the only child; pin it low

    # No nav here in either phase: phase 1 has none, and in phase 2 it lives
    # in the fixed page header. Rendering it here too is how you get two.
    return f"""  <header class="{classes}" id="top">
    <div class="{inner}">
{body}{cue}    </div>
  </header>"""


def pageheader(current, tall):
    """Phase 2's header: fixed to the window, carrying the nav and the wordmark.

    There is deliberately only ONE of these rather than a banner copy plus a
    separate bar that slides in. The wordmark starts pushed down to its hero
    position and rides up as you scroll until it comes to rest beside the nav,
    which is the compact bar. Because it is the same element throughout, there
    is no crossfade or handoff to go wrong — it is literally the same words
    moving.

    Figma puts the nav at y=60 in both the tall and the compact frame, so the
    nav never moves; only the wordmark travels, by 464-112 = 352px (22rem).
    """
    if not FULL:
        return ""
    rows = []
    for label, href in C.NAV:
        aria = ' aria-current="page"' if href == current else ""
        rows.append(f'        <a href="{href}"{aria}>{label}</a>')
    links = "\n".join(rows)
    mod = " pageheader--tall" if tall else ""
    return f"""  <div class="pageheader{mod}" id="pageheader">
    <div class="pageheader__bg" aria-hidden="true"></div>
    <div class="wrap pageheader__inner">
      <nav class="nav" aria-label="Site">
{links}
      </nav>
      <div class="wordmark pageheader__wordmark">
        <h1 class="wordmark__name">{C.WEDDING['names']}</h1>
        {meta_line(date_first=True)}
      </div>
    </div>
  </div>
"""


def contact_block():
    c = C.CONTACT
    return f"""      <div class="footer__contact">
        <p class="footer__contact-intro">Please contact Eliza &amp; Lucas should you have any questions.</p>
        <ul class="footer__details">
          <li>Email: <a href="mailto:{c['email']}">{c['email']}</a></li>
          <li>Phone: <a href="tel:{c['phone_href']}">{c['phone']}</a></li>
          <li>Website: <a href="https://{c['website']}">{c['website']}</a></li>
        </ul>
        <p class="footer__contact-short">Contact <a href="mailto:{c['email']}">{c['email']}</a> with questions.</p>
      </div>"""


def footer():
    """One footer for every page.

    The save-the-date footer is the reference: contact block on the left,
    photo on the right, back-to-top underneath. The full site uses exactly
    that and adds a nav row above it — so the two phases never diverge
    visually, which is the whole point of generating them from one place.
    """
    photo = ('      <div class="footer__photo">'
             '<img src="surfing.jpg" alt="Eliza and Lucas paddling out" /></div>')

    links = ""
    if FULL:
        by_label = {label: href for label, href in C.NAV}
        rows = "\n".join(
            f'          <a href="{by_label[label]}">{label}</a>'
            for label in C.FOOTER_NAV_ORDER
        )
        links = f"""      <nav class="footer__links">
{rows}
      </nav>
"""

    return f"""  <footer class="footer">
    <div class="wrap">
      <div class="footer__top">
        <p class="footer__name"><a href="{C.ENTRY_PAGE}">{C.WEDDING['names_short']}</a></p>
        {meta_line(date_first=True)}
      </div>
{links}      <div class="footer__cols footer__cols--stdate">
{contact_block()}
{photo}
      </div>
      <p class="back-to-top"><a href="#top"><span class="back-to-top__rule"></span>Back to top</a></p>
    </div>
  </footer>"""


def page(filename, title, main, tall=False, save_the_date=False, scripts=""):
    site_js = '\n  <script src="js/site.js"></script>' if FULL else ""
    body_class = ' class="phase2"' if FULL else ""
    html = f"""<!DOCTYPE html>
<html lang="en">
{GENERATED_BANNER}{head(title, filename)}
<body{body_class}>
{pageheader(filename, tall)}{banner(filename, tall, save_the_date)}

{main}

{footer()}{site_js}{scripts}
</body>
</html>
"""
    write(filename, html)


def write(filename, html):
    path = os.path.join(OUT_DIR, filename)
    os.makedirs(os.path.dirname(path) or OUT_DIR, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"  wrote {os.path.relpath(path, HERE)}")


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------

def rows(items):
    """The label / rule / text row pattern used by FAQs and Recommendations."""
    out = ['      <div class="rows">']
    for label, paras in items:
        out.append('        <div class="row">')
        out.append('          <div class="row__rule"></div>')
        out.append('          <div class="row__body">')
        out.append(f'            <h3 class="row__label">{label}</h3>')
        for p in paras:
            out.append(f'            <p class="row__text">{p}</p>')
        out.append("          </div>")
        out.append("        </div>")
    out.append("      </div>")
    return "\n".join(out)


def section(title, body, note=None, extra_class=""):
    cls = f"section {extra_class}".strip()
    note_html = f'\n      <p class="section__note">{note}</p>' if note else ""
    return f"""  <main class="{cls}">
    <div class="wrap">
      <h2 class="section__title">{title}</h2>{note_html}
{body}
    </div>
  </main>"""


def faq_section():
    return section("FAQs", rows(C.FAQS))


def rsvp_form():
    """The RSVP form.

    Only the code row is present at the start; the attending and dietary rows
    are revealed by js/rsvp.js once a code comes back from the server. They
    carry is-hidden in the markup rather than being injected later so the page
    doesn't reflow when they appear, and so the form still reads sensibly if
    the script fails to load.
    """
    return f"""      <form id="rsvp-form" class="rows" novalidate>
        <div class="row">
          <div class="row__rule"></div>
          <div class="row__body">
            <p class="row__text" id="rsvp-intro">Please enter your party code (found in the email). If you&rsquo;re
              responding for you and a guest (or your family), you&rsquo;ll be able to RSVP for your
              entire group.</p>
            <div class="code-entry">
              <input class="field code-entry__field" id="party-code" name="code" type="text"
                     autocomplete="off" aria-label="Party code" spellcheck="false" />
              <button class="code-entry__go" id="code-go" type="button"
                      aria-label="Look up your party"><span class="arrow"></span></button>
            </div>
          </div>
        </div>

        <div class="row is-hidden" id="step-guests">
          <div class="row__rule"></div>
          <div class="row__body">
            <p class="row__text">Who from your party will be attending?</p>
            <div class="guest-list" id="guest-list"></div>
          </div>
        </div>

        <div class="row is-hidden" id="step-diet">
          <div class="row__rule"></div>
          <div class="row__body">
            <p class="row__text">What are the guests&rsquo; dietary restrictions?</p>
            <div class="diet-list" id="diet-list"></div>
          </div>
        </div>

        <div class="row">
          <div></div>
          <div class="row__body">
            <button class="submit is-hidden" id="rsvp-submit" type="submit">Submit <span class="arrow"></span></button>
            <p class="form-msg" id="rsvp-msg" role="status" aria-live="polite"></p>
          </div>
        </div>
      </form>

      <!-- Replaces the whole form once an RSVP lands. -->
      <div class="rows is-hidden" id="rsvp-done">
        <div class="row">
          <div class="row__rule"></div>
          <div class="row__body">
            <p class="row__text">Thank you for RSVPing.</p>
            <p class="row__text">If you need to change your RSVP, please contact Eliza &amp; Lucas at
              <a href="mailto:{C.CONTACT['email']}">{C.CONTACT['email']}</a></p>
          </div>
        </div>
      </div>"""


def itinerary_section():
    out = []
    for day, events in C.ITINERARY:
        out.append(f'      <h3 class="day">{day}</h3>')
        for time, name, optional, paras in events:
            opt = '<span class="opt">Optional:</span> ' if optional else ""
            out.append('      <div class="event">')
            out.append(f'        <p class="event__time">{time}</p>')
            out.append('        <div class="event__rule"></div>')
            out.append('        <div class="event__body">')
            out.append(f'          <h3 class="event__name">{opt}{name}</h3>')
            for p in paras:
                out.append(f'          <p class="event__text">{p}</p>')
            out.append("        </div>")
            out.append("      </div>")
    return section("Itinerary", "\n".join(out))


# ---------------------------------------------------------------------------
# Pages
# ---------------------------------------------------------------------------

SAVE_THE_DATE_PAGES = ["home.html"]
FULL_PAGES = ["home.html", "itinerary.html", "recommendations.html", "faqs.html"]
ALL_PAGES = sorted(set(SAVE_THE_DATE_PAGES + FULL_PAGES) | {"homepage.html"})


RSVP_DEMO_JS = """/* Fake RSVP backend — LOCAL PREVIEW ONLY.
 *
 * build.py writes this file into _phase2/ and nowhere else, so it cannot
 * reach the real site. It exists so the whole RSVP flow can be clicked
 * through before the Apps Script is deployed.
 *
 * A handful of real parties, enough to exercise every path:
 *   BAILEY   four adults
 *   CASS     three, one of them a child
 *   ETHAN    a party of one
 *   LORETTA  six, the largest on the list
 *   USED     already RSVP'd — shows the locked message
 *
 * Anything else gives the not-found message. Submitting locks that code for
 * the rest of the page's life, so you can test the lock by submitting and
 * then entering the same code again.
 */
(function () {
  var PARTIES = {
    bailey:  { code: 'BAILEY',  leader: 'Karen',   names: ['Karen', 'Perry', 'Brendon', 'Jaiden'] },
    cass:    { code: 'CASS',    leader: 'Cass',    names: ['Cass', 'Alessia', 'Carsten'], child: 'Alessia' },
    ethan:   { code: 'ETHAN',   leader: 'Ethan',   names: ['Ethan'] },
    loretta: { code: 'LORETTA', leader: 'Loretta', names: ['Loretta', 'Tobi', 'Elijah', 'Isaiah', 'Brielle', 'Judas'] }
  };
  var locked = { used: true };

  function wait(ms, value) {
    return new Promise(function (res) { setTimeout(function () { res(value); }, ms); });
  }

  window.RSVP_DEMO = function (kind, payload) {
    var key = String(payload.code || '').trim().toLowerCase();

    if (kind === 'lookup') {
      if (locked[key]) {
        return wait(350, { ok: false, locked: true,
          error: 'This party has already RSVP\\u2019d, please message Eliza & Lucas at '
               + 'elizakeale@gmail.com to change your response.' });
      }
      var p = PARTIES[key];
      if (!p) {
        return wait(350, { ok: false,
          error: 'This code is not valid, please check spelling and use all caps.' });
      }
      return wait(350, { ok: true, party: {
        code: p.code,
        leader: p.leader,
        greeting: 'Found you \\u2014 ' + p.leader + '\\u2019s party.',
        guests: p.names.map(function (n) {
          return { id: key + '|' + n.toLowerCase(), name: n,
                   child: p.child === n ? 'child' : '', attending: false, dietary: '' };
        })
      }});
    }

    locked[key] = true;
    var going = (payload.guests || []).filter(function (g) { return g.attending; });
    console.log('[RSVP demo] would write to the sheet:',
                JSON.parse(JSON.stringify(payload)));
    return wait(450, { ok: true, attending: going.length });
  };

  console.log('[RSVP demo] active — try BAILEY, CASS, ETHAN, LORETTA, or USED (locked).');
})();
"""


def build(preview=False):
    global FULL, OUT_DIR

    if preview:
        FULL, OUT_DIR = True, PHASE2_DIR
        for stale_dir in LEGACY_OUT_DIRS + ["_phase2"]:
            shutil.rmtree(os.path.join(HERE, stale_dir), ignore_errors=True)
        os.makedirs(PHASE2_DIR, exist_ok=True)
        print("PHASE 2 PREVIEW — written to _phase2/ only.")
        print("Nothing here is committed or published.\n")
    else:
        FULL, OUT_DIR = C.PHASE in PHASE_2_NAMES, HERE
        print(f"PHASE = {C.PHASE!r}")

    if FULL:
        # The demo backend loads before rsvp.js and only in the preview, so
        # the real site can never pick it up.
        rsvp_scripts = '\n  <script src="js/rsvp.js"></script>'
        if preview:
            rsvp_scripts = ('\n  <script src="js/rsvp-demo.js"></script>'
                            '\n  <script src="js/rsvp.js"></script>')
        page("home.html", "E &amp; L Wedding",
             section("RSVP", rsvp_form(),
                     note=f"We kindly ask you to RSVP by {C.WEDDING['rsvp_deadline']}.",
                     extra_class="rsvp"),
             tall=True,
             scripts=rsvp_scripts)
        page("itinerary.html", "Itinerary &mdash; E &amp; L Wedding", itinerary_section())
        page("recommendations.html", "Recommendations &mdash; E &amp; L Wedding",
             section("Recommendations", rows(C.RECOMMENDATIONS)))
        page("faqs.html", "FAQs &mdash; E &amp; L Wedding", faq_section())
        live = FULL_PAGES
    else:
        page("home.html", "E &amp; L Wedding &mdash; Save the Date",
             faq_section(), tall=True, save_the_date=True)
        live = SAVE_THE_DATE_PAGES

    # Keep old shared links working: homepage.html was the entry page before
    # the pages were consolidated. Remove once no one is using that URL.
    write("homepage.html", f"""<!DOCTYPE html>
<html lang="en">
{GENERATED_BANNER}<head>
  <meta charset="UTF-8" />
  <meta name="robots" content="noindex, nofollow" />
  <meta http-equiv="refresh" content="0; url={C.ENTRY_PAGE}" />
  <link rel="canonical" href="{C.ENTRY_PAGE}" />
  <title>E &amp; L Wedding</title>
</head>
<body>
  <p>Redirecting to <a href="{C.ENTRY_PAGE}">the wedding site</a>&hellip;</p>
  <script>location.replace('{C.ENTRY_PAGE}');</script>
</body>
</html>
""")
    live = list(live) + ["homepage.html"]

    if preview:
        for name in PHASE2_ASSETS:
            src = os.path.join(HERE, name)
            if not os.path.exists(src):
                continue
            dst = os.path.join(PHASE2_DIR, name)
            if os.path.isdir(src):
                shutil.copytree(src, dst, dirs_exist_ok=True)
            else:
                shutil.copy2(src, dst)
        # The gate is skipped on purpose: the preview drops you straight onto
        # the site rather than making you retype the password each reload.
        with open(os.path.join(PHASE2_DIR, "js", "rsvp-demo.js"), "w", encoding="utf-8") as f:
            f.write(RSVP_DEMO_JS)
        print("\n  copied assets (css, js, images)")
        print("  wrote _phase2/js/rsvp-demo.js  — fake backend, preview only")
        print("     try codes: BAILEY  CASS  ETHAN  LORETTA  USED(locked)  NOPE(not found)")
        print("\n  Open it with either of these:")
        print("    VS Code   — right-click _phase2/home.html, 'Open with Live Server'")
        print(f"    Terminal  — cd '{HERE}/_phase2' && python3 -m http.server 8080")
        print("                then go to http://localhost:8080/home.html")
        print("\n  _phase2/ is gitignored. Rebuild any time with: python3 build.py --phase2")
        print("  Don't rename it — the leading underscore is what keeps it out of git.")
        print("\nDone.")
        return

    stale = [p for p in ALL_PAGES if p not in live and os.path.exists(os.path.join(HERE, p))]
    if stale:
        print("\n  Stale pages from another phase (delete these so they don't ship):")
        for p in stale:
            print(f"    git rm {p}")

    update_gate()
    print("\nDone.")


GATE_START = "<!-- social-meta:start (generated by build.py — do not edit by hand) -->"
GATE_END = "<!-- social-meta:end -->"


def update_gate():
    """Keep index.html's shareable bits in sync with content.py.

    index.html is hand-written (it carries the password logic), so it is not
    regenerated. But the link-preview tags, the redirect target and the asset
    versions must match the rest of the site or the gate quietly drifts — and
    the gate is the page people actually share, so its tags are the ones that
    matter most.
    """
    path = os.path.join(HERE, "index.html")
    if not os.path.exists(path):
        print("\n  ! index.html (password gate) is missing.")
        return

    with open(path, encoding="utf-8") as f:
        gate = original = f.read()

    block = f"{GATE_START}\n{social_meta()}\n  {GATE_END}"
    if GATE_START in gate and GATE_END in gate:
        gate = re.sub(re.escape(GATE_START) + r".*?" + re.escape(GATE_END),
                      block, gate, flags=re.S)
    else:
        gate = gate.replace("</head>", f"{block}\n</head>", 1)

    # Redirect target
    gate, n = re.subn(r"(location(?:\.href|\.replace)?\s*[=(]\s*')[^']+\.html(')",
                      rf"\g<1>{C.ENTRY_PAGE}\g<2>", gate)
    if n == 0:
        print("\n  ! Could not find the redirect target in index.html — check it by hand.")

    # Asset versions
    gate = re.sub(r"(favicon\.(?:ico|png)\?v=)\d+", rf"\g<1>{C.ASSET_VERSION}", gate)

    if gate != original:
        with open(path, "w", encoding="utf-8") as f:
            f.write(gate)
        print("  updated index.html (link-preview tags, redirect, asset versions)")
    else:
        print("  index.html already up to date")


if __name__ == "__main__":
    args = set(sys.argv[1:])
    flags = {"--phase2", "--preview"}          # --preview kept as an alias
    if args - flags:
        print(__doc__)
        print("Usage:\n  python3 build.py            build the live site\n"
              "  python3 build.py --phase2   build phase 2 into _phase2/ to look at")
        sys.exit(1)
    build(preview=bool(args & flags))
