#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
E & L Wedding — static site generator.

Run:
  python3 build.py            build the live site for the current PHASE
  python3 build.py --phase2   build phase 2 into _phase2/ to look at,
                              without changing or publishing anything live

Reads every piece of copy from content.py and writes the HTML pages for the
current PHASE. Pages that don't belong to the current phase are reported as
stale so you can remove them — nothing about an unreleased page ships.

All *.html files except index.html are generated. Edit content.py, not HTML.
"""

import os
import re
import shutil
import sys

import content as C

HERE = os.path.dirname(os.path.abspath(__file__))

# Where pages get written. Normally the repo root; the preview build points it
# at _preview/ so the full site can be looked at without touching what ships.
OUT_DIR = HERE
PHASE2_DIR = os.path.join(HERE, "_phase2")
# Older/renamed output folders, cleaned up on build so a stray copy can't be
# served by Live Server or picked up by git.
LEGACY_OUT_DIRS = ["_preview", "preview", "Preview"]

# Files the preview copies alongside the generated pages so it renders properly.
# Clean URLs. Every generated page is written as <slug>/index.html, so it is
# served as lucasandeliza.com/<slug> with no .html on the end. That puts every
# page exactly one directory down, which is why assets and cross-links are all
# "../" — a constant, not a per-page calculation.
#
# index.html (the password gate) stays at the root, so the bare domain is the
# front door.
def slug(filename):
    """Where a page is served from. "" means the site root.

    In phase 1 the save-the-date IS the root: the gate is an overlay on the
    same page rather than a separate door, so there is no second URL anyone
    can go straight to. In phase 2 the root is the gate and the pages sit
    under their own names.
    """
    if filename == "home.html":
        return "rsvp" if FULL else ""
    return filename[:-5]          # itinerary.html -> itinerary


def prefix(filename):
    """How far up the assets are from this page."""
    return "" if slug(filename) == "" else "../"


def link(filename):
    """A link from one generated page to another. Every generated page is
    either at the root or one directory down, so this is one of two shapes."""
    s = slug(filename)
    return "./" if s == "" else f"../{s}/"


UP = "../"          # depth of the page being written; set by page()

PHASE2_ASSETS = ["css", "js", "orchid.jpg", "surfing.jpg",
                  "og-image.jpg", "favicon.ico", "favicon.png"]

GENERATED_BANNER = (
    "<!--\n"
    "  DO NOT EDIT THIS FILE.\n"
    "  Generated by build.py from content.py. Your changes will be overwritten\n"
    "  on the next build. Edit content.py and run: python3 build.py\n"
    "-->\n"
)

# "full" is still accepted as a synonym so an older content.py keeps working.
PHASE_2_NAMES = ("phase-2", "phase2", "full")
FULL = C.PHASE in PHASE_2_NAMES

# True only for --phase2 builds. The fake backend loads on every preview page
# (the itinerary needs it as much as the RSVP form does) and on none of the
# real ones.
PREVIEW = False


# ---------------------------------------------------------------------------
# Shared pieces
# ---------------------------------------------------------------------------

def social_meta(page=""):
    """Open Graph + Twitter tags, used for iMessage/SMS/WhatsApp/Slack previews.

    Every URL here is absolute on purpose: link-preview crawlers do not resolve
    relative paths, so a relative og:image silently yields a picture-less card.
    """
    m = C.META
    base = C.SITE_URL.rstrip("/")
    url = f"{base}/{slug(page)}" if page else f"{base}/"
    return f"""  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="E &amp; L Wedding" />
  <meta property="og:title" content="{m['title']}" />
  <meta property="og:description" content="{m['description']}" />
  <meta property="og:url" content="{url}" />
  <meta property="og:image" content="{base}/{m['image']}" />
  <meta property="og:image:secure_url" content="{base}/{m['image']}" />
  <meta property="og:image:type" content="image/jpeg" />
  <meta property="og:image:width" content="{m['image_w']}" />
  <meta property="og:image:height" content="{m['image_h']}" />
  <meta property="og:image:alt" content="Eliza and Lucas in the water at Rockpiles" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="{m['title']}" />
  <meta name="twitter:description" content="{m['description']}" />
  <meta name="twitter:image" content="{base}/{m['image']}" />
  <meta name="theme-color" content="#bcbc49" />"""


# ---------------------------------------------------------------------------
# The gate
#
# In phase 1 this is an overlay on the save-the-date itself, not a separate
# page. That is the whole point: a door with its own URL is a door people can
# walk around, and /savethedate was exactly that.
#
# Everything is scoped under #gate so it cannot reach the page underneath,
# which is a full stylesheet of its own.
#
# The page is hidden by CSS until <html> gets the "unlocked" class, and an
# inline script in the head sets that before the first paint if the session is
# still good — so a reload does not flash the door at someone already inside.
# With JavaScript off it stays shut, which is the right way to fail.
#
# None of this is real security. The content is in the page source, as it was
# when the door was its own page. It stops the link being walked around, not a
# determined reader.
# ---------------------------------------------------------------------------

GATE_STYLE = """
    #gate, #gate * { margin:0; padding:0; box-sizing:border-box; }
    html:not(.unlocked), html:not(.unlocked) body {
      width:100%; height:100%; overflow:hidden; background:#ede0e4;
    }
    html:not(.unlocked) #site { display:none; }
    html.unlocked #gate { display:none; }
    #gate { position:fixed; inset:0; z-index:9999;
            display:flex; align-items:center; justify-content:center; }
    #gate .bg { position:absolute; inset:0; width:100%; height:100%;
                object-fit:cover; object-position:center; }
    #gate .card { position:relative; z-index:2; display:flex; flex-direction:column;
                  align-items:center; width:clamp(200px, 22%, 329px); }
    #gate .photo { width:100%; aspect-ratio:329/215; object-fit:cover; display:block; }
    #gate .pw-input {
      display:block; width:100%; height:40px;
      background:#ffe993; border:none; outline:none;
      font-family:'Cormorant Upright',serif; font-weight:300;
      font-size:15px; letter-spacing:1px; color:#7f214d; text-align:center;
      padding:0 12px; -webkit-appearance:none; appearance:none;
      border-radius:0; caret-color:transparent;
    }
    #gate .pw-input::placeholder { color:#7f214d; opacity:1; }
    #gate .error {
      font-family:'Cormorant Infant',serif; font-style:italic;
      font-size:12px; color:#fff; text-align:center;
      margin-top:8px; min-height:18px;
      text-shadow:0 1px 3px rgba(0,0,0,0.5);
      opacity:0; transition:opacity 0.2s;
    }
    #gate .error.show { opacity:1; }
    @keyframes shake {
      0%,100%{transform:translateX(0)} 20%{transform:translateX(-7px)}
      40%{transform:translateX(7px)} 60%{transform:translateX(-5px)}
      80%{transform:translateX(5px)}
    }
    #gate .shake { animation:shake 0.38s ease; }
    #gate .pw-cursor { position:absolute; top:50%; left:calc(50% + 74px);
      transform:translateY(-50%); width:1px; height:15px; background:#7f214d;
      pointer-events:none; animation:blink 1.1s ease-in-out infinite; }
    #gate .pw-cursor.hidden { display:none; }
    @keyframes blink { 0%,100%{opacity:1} 50%{opacity:0} }
    @media (max-width:600px) {
      #gate .card { width:61.4vw; align-items:flex-start; }
      #gate #wrap { width:81.8vw !important; margin-top:7.3vh !important;
                    margin-left:calc(-10.1vw) !important; }
      #gate .pw-cursor { left:calc(50% + 55px); }
    }
"""


def gate_markup(up=""):
    return f'''  <div id="gate">
    <img class="bg" src="{up}orchid.jpg" alt="" />
    <div class="card">
      <img class="photo" src="{up}surfing.jpg" alt="Eliza and Lucas" />
      <div id="wrap" class="pw-input-wrap" style="margin-top: clamp(30px, 6.3vh, 62px); position:relative; width:100%;">
        <input id="input" class="pw-input" type="password" placeholder="ENTER PASSWORD" autocomplete="off" />
        <span class="pw-cursor" id="cursor"></span>
      </div>
      <p id="error" class="error">Incorrect password &mdash; please try again.</p>
    </div>
  </div>
'''


# Runs before the first paint, so someone already inside never sees the door
# flash. Deliberately duplicates the TTL from js/config.js: inlining it is what
# makes it early enough to matter, and both read the same stored value.
GATE_EARLY = """  <script>
    try {
      var s = JSON.parse(sessionStorage.getItem('elw.session') || 'null');
      if (s && s.t && (Date.now() - s.t) < 1800000) {
        document.documentElement.className = 'unlocked';
      }
    } catch (e) {}
  </script>"""


def head(title, page="", up="../", extra=""):
    v = C.ASSET_VERSION
    return f"""<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title}</title>
  <meta name="description" content="{C.META['description']}" />
  <meta name="robots" content="noindex, nofollow" />
{social_meta(page)}
  <link rel="icon" href="{up}favicon.ico?v={v}" sizes="any" />
  <link rel="icon" type="image/png" href="{up}favicon.png?v={v}" sizes="180x180" />
  <link rel="apple-touch-icon" href="{up}favicon.png?v={v}" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Cormorant+Infant:ital,wght@0,300;1,300&family=Cormorant+Upright:wght@300&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="{up}css/wedding.css?v={v}" />{extra}
</head>"""


def meta_line(date_first=True):
    """The date — rule — place strip used in the hero and the footer."""
    d = C.WEDDING["date_display"]
    p = C.WEDDING["place"]
    if date_first:
        return (f'<span class="meta"><span class="meta__date">{d}</span>'
                f'<span class="meta__rule"></span>'
                f'<span class="meta__place">{p}</span></span>')
    return (f'<span class="meta"><span class="meta__rule"></span>'
            f'<span class="meta__date">{d}</span>'
            f'<span class="meta__place">{p}</span></span>')


def banner(current, tall, save_the_date=False):
    classes = "banner banner--tall" if tall else "banner banner--short"
    if save_the_date:
        classes += " banner--stdate"

    if save_the_date or FULL:
        # The wordmark lives in the fixed page header in both phases, so it
        # can ride up the screen and settle into the bar. The banner is then
        # just the photo (and the cue, on a tall hero).
        body = ""
    else:
        body = f"""      <div>
        <div class="wordmark">
          <h1 class="wordmark__name">{C.WEDDING['names']}</h1>
          {meta_line(date_first=True)}
        </div>
      </div>
"""

    # The pulsing cue belongs to any full-height hero — it exists to say
    # "there is more below the fold". The short 260px banners open straight
    # onto their content, so a cue there would point at nothing.
    cue = '      <span class="scroll-cue" aria-hidden="true"></span>\n' if tall else ""
    inner = "wrap banner__inner"
    if tall:
        inner += " banner__inner--cue-only"   # cue is the only child; pin it low

    # No nav here in either phase: phase 1 has none, and in phase 2 it lives
    # in the fixed page header. Rendering it here too is how you get two.
    return f"""  <header class="{classes}" id="top">
    <div class="{inner}">
{body}{cue}    </div>
  </header>"""


def pageheader(current, tall, save_the_date=False):
    """Phase 2's header: fixed to the window, carrying the nav and the wordmark.

    There is deliberately only ONE of these rather than a banner copy plus a
    separate bar that slides in. The wordmark starts pushed down to its hero
    position and rides up as you scroll until it comes to rest beside the nav,
    which is the compact bar. Because it is the same element throughout, there
    is no crossfade or handoff to go wrong — it is literally the same words
    moving.

    Figma puts the nav at y=60 in both the tall and the compact frame, so the
    nav never moves; only the wordmark travels, by 464-112 = 352px (22rem).
    """
    if not (FULL or save_the_date):
        return ""

    if save_the_date:
        # Same one-element motion as phase 2, minus the nav: the wordmark
        # starts at its hero size and position and rides up into the bar.
        # "Save the date" and the tagline travel with it and fade out, since
        # neither belongs in a compact bar.
        mod = " pageheader--tall" if tall else ""
        return f"""  <div class="pageheader pageheader--stdate{mod}" id="pageheader">
    <div class="pageheader__bg" aria-hidden="true"></div>
    <div class="wrap pageheader__inner">
      <div class="wordmark pageheader__wordmark">
        <h1 class="wordmark__name"><a href="{link(C.ENTRY_PAGE)}">E &amp; L<span
          class="stdate__rest"> Wedding</span></a></h1>
        {meta_line(date_first=True)}
        <p class="stdate__label">{C.SAVE_THE_DATE['label']}</p>
        <p class="stdate__tagline">{C.SAVE_THE_DATE['tagline']}</p>
      </div>
    </div>
  </div>
"""

    rows = []
    for label, href in C.NAV:
        aria = ' aria-current="page"' if href == current else ""
        rows.append(f'        <a href="{link(href)}"{aria}>{label}</a>')
    links = "\n".join(rows)
    mod = " pageheader--tall" if tall else ""
    return f"""  <div class="pageheader{mod}" id="pageheader">
    <div class="pageheader__bg" aria-hidden="true"></div>
    <div class="wrap pageheader__inner">
      <nav class="nav" aria-label="Site">
{links}
      </nav>
      <div class="wordmark pageheader__wordmark">
        <h1 class="wordmark__name"><a href="{link(C.ENTRY_PAGE)}">{C.WEDDING['names']}</a></h1>
        {meta_line(date_first=True)}
      </div>
    </div>
  </div>
"""


def contact_block():
    c = C.CONTACT
    return f"""      <div class="footer__contact">
        <p class="footer__contact-intro">Please contact Eliza &amp; Lucas should you have any questions.</p>
        <ul class="footer__details">
          <li>Email: <a href="mailto:{c['email']}">{c['email']}</a></li>
          <li>Phone: <a href="tel:{c['phone_href']}">{c['phone']}</a></li>
          <li>Website: <a href="#top">{c['website']}</a></li>
        </ul>
        <p class="footer__contact-short">Contact <a href="mailto:{c['email']}">{c['email']}</a> with questions.</p>
      </div>"""


def footer():
    """One footer for every page.

    The save-the-date footer is the reference: contact block on the left,
    photo on the right, back-to-top underneath. The full site uses exactly
    that and adds a nav row above it — so the two phases never diverge
    visually, which is the whole point of generating them from one place.
    """
    photo = ('      <div class="footer__photo">'
             f'<img src="{UP}surfing.jpg" alt="Eliza and Lucas paddling out" /></div>')

    links = ""
    if FULL:
        by_label = {label: href for label, href in C.NAV}
        rows = "\n".join(
            f'          <a href="{link(by_label[label])}">{label}</a>'
            for label in C.FOOTER_NAV_ORDER
        )
        links = f"""      <nav class="footer__links">
{rows}
      </nav>
"""

    return f"""  <footer class="footer">
    <div class="wrap">
      <div class="footer__top">
        <p class="footer__name"><a href="{link(C.ENTRY_PAGE)}">{C.WEDDING['names_short']}</a></p>
        {meta_line(date_first=True)}
      </div>
{links}      <div class="footer__cols footer__cols--stdate">
{contact_block()}
{photo}
      </div>
      <p class="back-to-top"><a href="#top"><span class="back-to-top__rule"></span>Back to top</a></p>
    </div>
  </footer>"""


def page(filename, title, main, tall=False, save_the_date=False, scripts=""):
    global UP
    up = UP = prefix(filename)

    # The save-the-date is the site root, so the gate rides on it rather than
    # standing in front of it as its own URL.
    gated = save_the_date and slug(filename) == ""

    demo_js = f'\n  <script src="{up}js/rsvp-demo.js"></script>' if (FULL and PREVIEW) else ""
    site_js = ((demo_js + f'\n  <script src="{up}js/config.js"></script>')
               if FULL else "")
    if gated:
        site_js += f'\n  <script src="{up}js/config.js"></script>'
    if FULL or save_the_date:
        site_js += f'\n  <script src="{up}js/site.js"></script>'
    if gated:
        site_js += f'\n  <script src="{up}js/gate.js"></script>'

    body_class = ' class="phase2"' if FULL else ""
    extra_head = f"\n  <style>{GATE_STYLE}  </style>\n{GATE_EARLY}" if gated else ""
    body = f"""{pageheader(filename, tall, save_the_date)}{banner(filename, tall, save_the_date)}

{main}

{footer()}"""
    if gated:
        body = gate_markup(up) + '  <div id="site">\n' + body + "\n  </div>"

    html = f"""<!DOCTYPE html>
<html lang="en">
{GENERATED_BANNER}{head(title, filename, up, extra_head)}
<body{body_class}>
{body}{site_js}{scripts}
</body>
</html>
"""
    write(filename, html)


def write(filename, html, literal=False):
    rel = filename if literal else os.path.join(slug(filename), "index.html")
    path = os.path.join(OUT_DIR, rel)
    os.makedirs(os.path.dirname(path) or OUT_DIR, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"  wrote {os.path.relpath(path, HERE)}")


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------

def rows(items):
    """The label / rule / text row pattern used by FAQs and Recommendations.

    A bare string in the list is a group heading ("General", "Wedding Day"),
    styled like the itinerary's day headings because it does the same job.
    """
    out = ['      <div class="rows">']
    for item in items:
        if isinstance(item, str):
            out.append(f'        <h3 class="group">{item}</h3>')
            continue
        label, paras = item
        out.append('        <div class="row">')
        out.append('          <div class="row__rule"></div>')
        out.append('          <div class="row__body">')
        out.append(f'            <h3 class="row__label">{label}</h3>')
        for p in paras:
            out.append(f'            <p class="row__text">{p}</p>')
        out.append("          </div>")
        out.append("        </div>")
    out.append("      </div>")
    return "\n".join(out)


def section(title, body, note=None, extra_class=""):
    cls = f"section {extra_class}".strip()
    note_html = f'\n      <p class="section__note">{note}</p>' if note else ""
    return f"""  <main class="{cls}">
    <div class="wrap">
      <h2 class="section__title">{title}</h2>{note_html}
{body}
    </div>
  </main>"""


def faq_section():
    """The save-the-date page answers only what can honestly be answered
    before invitations go out; the phase-2 page answers everything."""
    if FULL:
        return section("FAQs", rows(C.FAQS))
    return section("FAQs", rows(C.FAQS_SHORT))


def rsvp_form():
    """The RSVP form.

    Only the code row is present at the start; the attending and dietary rows
    are revealed by js/rsvp.js once a code comes back from the server. They
    carry is-hidden in the markup rather than being injected later so the page
    doesn't reflow when they appear, and so the form still reads sensibly if
    the script fails to load.
    """
    return f"""      <form id="rsvp-form" class="rows" novalidate>
        <div class="row">
          <div class="row__rule"></div>
          <div class="row__body">
            <p class="row__text" id="rsvp-intro">Please enter your party code (found in the email). If you&rsquo;re
              responding for you and a guest (or your family), you&rsquo;ll be able to RSVP for your
              entire group.</p>
            <div class="code-entry">
              <input class="field code-entry__field" id="party-code" name="code" type="text"
                     autocomplete="off" aria-label="Party code" spellcheck="false" />
              <button class="code-entry__go" id="code-go" type="button"
                      aria-label="Look up your party"><span class="arrow"></span></button>
            </div>
          </div>
        </div>

        <div class="row is-hidden" id="step-guests">
          <div class="row__rule"></div>
          <div class="row__body">
            <p class="row__text">Who from your party will be attending?</p>
            <div class="guest-list" id="guest-list"></div>
          </div>
        </div>

        <div class="row is-hidden" id="step-diet">
          <div class="row__rule"></div>
          <div class="row__body">
            <p class="row__text">What are the guests&rsquo; dietary restrictions?</p>
            <div class="diet-list" id="diet-list"></div>
          </div>
        </div>

        <div class="row">
          <div></div>
          <div class="row__body">
            <button class="submit is-hidden" id="rsvp-submit" type="submit">Submit <span class="arrow"></span></button>
            <p class="form-msg" id="rsvp-msg" role="status" aria-live="polite"></p>
          </div>
        </div>
      </form>

      <!-- Replaces the whole form once an RSVP lands. -->
      <div class="rows is-hidden" id="rsvp-done">
        <div class="row">
          <div class="row__rule"></div>
          <div class="row__body">
            <p class="row__text">Thank you for RSVPing.</p>
            <p class="row__text">If you need to change your RSVP, please contact Eliza &amp; Lucas at
              <a href="mailto:{C.CONTACT['email']}">{C.CONTACT['email']}</a></p>
          </div>
        </div>
      </div>"""


def write_itinerary_seed():
    """Write rsvp-backend/itinerary-seed.tsv from C.ITINERARY.

    The itinerary page ships empty and is filled by the Apps Script, so the
    schedule lives in the spreadsheet rather than in the HTML — that is what
    lets an event be withheld from a party who isn't invited, instead of
    hidden in CSS where anyone could read it in the page source.

    But a spreadsheet is a poor place to keep the master copy: it drifts from
    Figma and nobody can diff it. So content.py stays the source, this writes
    the paste-ready file, and the sheet is a copy you refresh when it changes.
    """
    path = os.path.join(HERE, "rsvp-backend", "itinerary-seed.tsv")
    rows = ["\t".join(C.ITINERARY_FIELDS)]

    def cell(v):
        # Tabs and newlines would break the paste; the site's own entities
        # mean nothing in a spreadsheet, so they are resolved here.
        s = str(v or "")
        s = s.replace("&ndash;", "\u2013").replace("&mdash;", "\u2014")
        s = s.replace("&amp;", "&").replace("&nbsp;", " ")
        return re.sub(r"\s+", " ", s).strip()

    # Sheets helpfully parses "Monday, October 18" into a date (guessing the
    # WRONG year) and "10 PM" into a time in 1899. A leading apostrophe is the
    # one thing it always reads as "this cell is text"; it is not displayed and
    # not returned by getValues(), so the script sees the string we wrote.
    def text(v):
        v = cell(v)
        return ("'" + v) if v else v

    for day, events in C.ITINERARY:
        for ev in events:
            row = [text(day), text(ev.get("time")), cell(ev.get("name")),
                   "Yes" if ev.get("optional") else ""]
            row += [cell(ev.get(f)) for f in C.ITINERARY_FIELDS[4:]]
            rows.append("\t".join(row))

    body = "\n".join(rows) + "\n"
    if not os.path.exists(path) or open(path, encoding="utf-8").read() != body:
        with open(path, "w", encoding="utf-8") as f:
            f.write(body)
        print("  wrote rsvp-backend/itinerary-seed.tsv"
              "  — re-paste this into the sheet's Itinerary tab")


# ---------------------------------------------------------------------------
# Pages
# ---------------------------------------------------------------------------

SAVE_THE_DATE_PAGES = ["home.html"]
FULL_PAGES = ["home.html", "itinerary.html", "recommendations.html", "faqs.html"]
ALL_PAGES = sorted(set(SAVE_THE_DATE_PAGES + FULL_PAGES) | {"homepage.html"})


RSVP_DEMO_JS = """/* Fake RSVP backend — LOCAL PREVIEW ONLY.
 *
 * build.py writes this file into _phase2/ and nowhere else, so it cannot
 * reach the real site. It exists so the whole RSVP flow can be clicked
 * through before the Apps Script is deployed.
 *
 * A handful of real parties, enough to exercise every path:
 *   BAILEY   four adults
 *   CASS     three, one of them a child
 *   ETHAN    a party of one
 *   LORETTA  six, the largest on the list
 *   USED     already RSVP'd — shows the locked message
 *
 * Anything else gives the not-found message. Submitting locks that code for
 * the rest of the page's life, so you can test the lock by submitting and
 * then entering the same code again.
 */
(function () {
  var PARTIES = {
    bailey:  { code: 'BAILEY',  leader: 'Karen',   names: ['Karen', 'Perry', 'Brendon', 'Jaiden'] },
    cass:    { code: 'CASS',    leader: 'Cass',    names: ['Cass', 'Alessia', 'Carsten'], child: 'Alessia' },
    ethan:   { code: 'ETHAN',   leader: 'Ethan',   names: ['Ethan'] },
    loretta: { code: 'LORETTA', leader: 'Loretta', names: ['Loretta', 'Tobi', 'Elijah', 'Isaiah', 'Brielle', 'Judas'] }
  };
  var locked = { used: true };

  // Who is invited to what, mirroring the guest sheet's Welcome BBQ? / Beach
  // Day columns. CASS gets the BBQ, LORETTA doesn't — enter each and compare.
  var INVITES = {
    bailey:  ['welcome bbq?'],
    cass:    ['welcome bbq?', 'beach day'],
    ethan:   ['welcome bbq?', 'beach day'],
    loretta: []
  };

  var EVENTS = [
    { day: 'Wednesday, February 9', time: '11:00 AM – 3:00 PM', name: 'Beach Day',
      optional: true, audience: 'beach day',
      body: 'Tents up at Makapu\u2019u Beach Park. Bring sunscreen and a towel.',
      location: 'Makapu\u2019u Beach Park, O\u2019ahu', parking: 'Easy on a weekday.' },
    { day: 'Thursday, February 10', time: '5:00 PM – 9:00 PM', name: 'Welcome BBQ',
      optional: false, audience: 'welcome bbq?',
      body: 'A welcome BBQ for family and close friends.',
      location: 'Kauhale Beach Cove, Kane\u2019ohe', parking: 'Guest spots plus street parking.' },
    { day: 'Saturday, February 12', time: '11:30 AM – 2:30 PM', name: 'Reception Lunch',
      optional: false, audience: '',
      body: 'Lunch with mimosas overlooking Haiku Gardens.',
      location: 'Hale\u2019iwa Joe\u2019s Haiku Gardens, Kane\u2019ohe', parking: 'Plenty on site.' },
    { day: 'Sunday, February 13', time: '5:00 PM – 9:00 PM', name: 'Sunset Cruise',
      optional: true, audience: '',
      body: 'Totally optional. Takes off from Honolulu.', location: '', parking: '' }
  ];

  function wait(ms, value) {
    return new Promise(function (res) { setTimeout(function () { res(value); }, ms); });
  }

  window.RSVP_DEMO = function (kind, payload) {
    var key = String((payload && payload.code) || '').trim().toLowerCase();

    if (kind === 'auth') {
      if (key === 'rockpiles') return wait(300, { ok: true, kind: 'master' });
      var known = PARTIES[key];
      return wait(300, known ? { ok: true, kind: 'party', code: known.code }
                             : { ok: false });
    }

    if (kind === 'itinerary') {
      var mine = key && key !== 'rockpiles' ? (INVITES[key] || []) : null;
      var visible = EVENTS.filter(function (ev) {
        if (!ev.audience) return true;            // everyone
        if (mine === null) return true;           // shared password sees all
        return mine.indexOf(ev.audience) !== -1;
      });
      return wait(350, { ok: true, events: visible });
    }

    if (kind === 'lookup') {
      if (locked[key]) {
        return wait(350, { ok: false, locked: true,
          error: 'This party has already RSVP\\u2019d, please message Eliza & Lucas at '
               + 'elizakeale@gmail.com to change your response.' });
      }
      var p = PARTIES[key];
      if (!p) {
        return wait(350, { ok: false,
          error: 'This code is not valid, please check spelling and use all caps.' });
      }
      return wait(350, { ok: true, party: {
        code: p.code,
        leader: p.leader,
        greeting: 'Found you \\u2014 ' + p.leader + '\\u2019s party.',
        guests: p.names.map(function (n) {
          return { id: key + '|' + n.toLowerCase(), name: n,
                   child: p.child === n ? 'child' : '', attending: false, dietary: '' };
        })
      }});
    }

    locked[key] = true;
    var going = (payload.guests || []).filter(function (g) { return g.attending; });
    console.log('[RSVP demo] would write to the sheet:',
                JSON.parse(JSON.stringify(payload)));
    return wait(450, { ok: true, attending: going.length });
  };

  console.log('[RSVP demo] active — try BAILEY, CASS, ETHAN, LORETTA, or USED (locked).');
})();
"""


def build(preview=False):
    global FULL, OUT_DIR, PREVIEW
    PREVIEW = preview

    if preview:
        FULL, OUT_DIR = True, PHASE2_DIR
        for stale_dir in LEGACY_OUT_DIRS + ["_phase2"]:
            shutil.rmtree(os.path.join(HERE, stale_dir), ignore_errors=True)
        os.makedirs(PHASE2_DIR, exist_ok=True)
        print("PHASE 2 PREVIEW — written to _phase2/ only.")
        print("Nothing here is committed or published.\n")
    else:
        FULL, OUT_DIR = C.PHASE in PHASE_2_NAMES, HERE
        print(f"PHASE = {C.PHASE!r}")

    if FULL:
        # The demo backend loads before rsvp.js and only in the preview, so
        # the real site can never pick it up.
        rsvp_scripts = '\n  <script src="../js/rsvp.js"></script>'
        page("home.html", "E &amp; L Wedding",
             section("RSVP", rsvp_form(),
                     note=f"We kindly ask you to RSVP by {C.WEDDING['rsvp_deadline']}.",
                     extra_class="rsvp"),
             tall=True,
             scripts=rsvp_scripts)
        page("itinerary.html", "Itinerary &mdash; E &amp; L Wedding",
             section("Itinerary", '      <div class="rows" id="itinerary"></div>'),
             scripts='\n  <script src="../js/itinerary.js"></script>')
        page("recommendations.html", "Recommendations &mdash; E &amp; L Wedding",
             section("Recommendations", rows(C.RECOMMENDATIONS)))
        page("faqs.html", "FAQs &mdash; E &amp; L Wedding", faq_section())
        live = FULL_PAGES
    else:
        page("home.html", "E &amp; L Wedding &mdash; Save the Date",
             faq_section(), tall=True, save_the_date=True)
        live = SAVE_THE_DATE_PAGES

    # Keep old shared links working: homepage.html was the entry page before
    # the pages were consolidated. Remove once no one is using that URL.
    write("homepage.html", f"""<!DOCTYPE html>
<html lang="en">
{GENERATED_BANNER}<head>
  <meta charset="UTF-8" />
  <meta name="robots" content="noindex, nofollow" />
  <meta http-equiv="refresh" content="0; url={slug(C.ENTRY_PAGE)}/" />
  <link rel="canonical" href="{slug(C.ENTRY_PAGE)}/" />
  <title>E &amp; L Wedding</title>
</head>
<body>
  <p>Redirecting to <a href="{slug(C.ENTRY_PAGE)}/">the wedding site</a>&hellip;</p>
  <script>location.replace('{slug(C.ENTRY_PAGE)}/');</script>
</body>
</html>
""", literal=True)
    live = list(live) + ["homepage.html"]

    if preview:
        for name in PHASE2_ASSETS:
            src = os.path.join(HERE, name)
            if not os.path.exists(src):
                continue
            dst = os.path.join(PHASE2_DIR, name)
            if os.path.isdir(src):
                shutil.copytree(src, dst, dirs_exist_ok=True)
            else:
                shutil.copy2(src, dst)
        # The gate is skipped on purpose: the preview drops you straight onto
        # the site rather than making you retype the password each reload.
        with open(os.path.join(PHASE2_DIR, "js", "rsvp-demo.js"), "w", encoding="utf-8") as f:
            f.write(RSVP_DEMO_JS)
        print("\n  copied assets (css, js, images)")
        print("  wrote _phase2/js/rsvp-demo.js  — fake backend, preview only")
        print("     try codes: BAILEY  CASS  ETHAN  LORETTA  USED(locked)  NOPE(not found)")
        print("\n  Open it with either of these:")
        print("    VS Code   — right-click _phase2/home.html, 'Open with Live Server'")
        print(f"    Terminal  — cd '{HERE}/_phase2' && python3 -m http.server 8080")
        print("                then go to http://localhost:8080/home.html")
        print("\n  _phase2/ is gitignored. Rebuild any time with: python3 build.py --phase2")
        print("  Don't rename it — the leading underscore is what keeps it out of git.")
        print("\nDone.")
        return

    stale = [p for p in ALL_PAGES
             if p not in live and os.path.exists(os.path.join(HERE, slug(p), "index.html"))]
    flat = [p for p in ALL_PAGES
            if p != "homepage.html" and os.path.exists(os.path.join(HERE, p))]
    if stale or flat:
        print("\n  Left over from an earlier build (delete so they don't ship):")
        for p in stale:
            print(f"    git rm -r {slug(p)}")
        for p in flat:
            dest = f"/{slug(p)}/" if slug(p) else "the site root"
            print(f"    git rm {p}   # replaced by {dest}")

    write_itinerary_seed()
    update_gate()
    print("\nDone.")


GATE_START = "<!-- social-meta:start (generated by build.py — do not edit by hand) -->"
GATE_END = "<!-- social-meta:end -->"


def update_gate():
    """Keep index.html's shareable bits in sync with content.py.

    index.html is hand-written (it carries the password logic), so it is not
    regenerated. But the link-preview tags, the redirect target and the asset
    versions must match the rest of the site or the gate quietly drifts — and
    the gate is the page people actually share, so its tags are the ones that
    matter most.
    """
    if not FULL:
        return          # phase 1 generates index.html; nothing to patch in
    path = os.path.join(HERE, "index.html")
    if not os.path.exists(path):
        print("\n  ! index.html (password gate) is missing.")
        return

    with open(path, encoding="utf-8") as f:
        gate = original = f.read()

    block = f"{GATE_START}\n{social_meta()}\n  {GATE_END}"
    if GATE_START in gate and GATE_END in gate:
        gate = re.sub(re.escape(GATE_START) + r".*?" + re.escape(GATE_END),
                      block, gate, flags=re.S)
    else:
        gate = gate.replace("</head>", f"{block}\n</head>", 1)

    # Redirect target. The old inline gate held it in a location.href; the
    # current one keeps it in js/config.js, so update whichever is in use.
    gate, n = re.subn(r"(location(?:\.href|\.replace)?\s*[=(]\s*')[^']+\.html(')",
                      rf"\g<1>{C.ENTRY_PAGE}\g<2>", gate)
    if n == 0 and "js/gate.js" not in gate:
        print("\n  ! Could not find the redirect target in index.html — check it by hand.")

    cfg_path = os.path.join(HERE, "js", "config.js")
    if os.path.exists(cfg_path):
        with open(cfg_path, encoding="utf-8") as f:
            cfg = before_cfg = f.read()
        cfg = re.sub(r"(window\.ELW\.ENTRY_PAGE\s*=\s*')[^']*(')",
                     rf"\g<1>{slug(C.ENTRY_PAGE)}/\g<2>", cfg)
        if cfg != before_cfg:
            with open(cfg_path, "w", encoding="utf-8") as f:
                f.write(cfg)
            print("  updated js/config.js (entry page)")

    # Asset versions
    gate = re.sub(r"(favicon\.(?:ico|png)\?v=)\d+", rf"\g<1>{C.ASSET_VERSION}", gate)

    # The gate loads config.js + gate.js. Its own inline <script> is replaced
    # the first time, so the password logic lives in one reviewable file
    # rather than inline in a 6KB page.
    tags = (f'  <script src="js/config.js?v={C.ASSET_VERSION}"></script>\n'
            f'  <script src="js/gate.js?v={C.ASSET_VERSION}"></script>\n')
    if "js/gate.js" in gate:
        gate = re.sub(r'  <script src="js/config\.js[^"]*"></script>\n'
                      r'  <script src="js/gate\.js[^"]*"></script>\n', tags, gate)
    else:
        # Drop the inline script and put the two files in its place.
        gate = re.sub(r"  <script>.*?</script>\n", tags, gate, count=1, flags=re.S)

    if gate != original:
        with open(path, "w", encoding="utf-8") as f:
            f.write(gate)
        print("  updated index.html (link-preview tags, redirect, asset versions)")
    else:
        print("  index.html already up to date")


if __name__ == "__main__":
    args = set(sys.argv[1:])
    flags = {"--phase2", "--preview"}          # --preview kept as an alias
    if args - flags:
        print(__doc__)
        print("Usage:\n  python3 build.py            build the live site\n"
              "  python3 build.py --phase2   build phase 2 into _phase2/ to look at")
        sys.exit(1)
    build(preview=bool(args & flags))
